In [42]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
c

In [7]:
import  sklearn
sklearn.__version__

'0.23.2'

In [51]:
from sklearn.experimental import enable_iterative_imputer

In [52]:
from sklearn.impute import IterativeImputer

In [33]:
df=c

In [11]:
df


age  experience  salary
0  25.0         NaN    50.0
1  27.0         3.0     NaN
2  29.0         5.0   110.0
3  31.0         7.0   140.0
4  33.0         9.0   170.0
5   NaN        11.0   200.0


imp=IterativeImputer(estimator=lr,max_iter=30,tol=1e-3,imputation_order="roman",Verbose=2)

In [12]:
df.corr()

age  experience  salary
age         1.0         1.0     1.0
experience  1.0         1.0     1.0
salary      1.0         1.0     1.0

In [48]:
lr=LinearRegression()

In [54]:

imp=IterativeImputer(estimator=lr,verbose=1, max_iter= 5,tol=1e-3,imputation_order="roman")
 

In [55]:
imp.fit_transform(df)

[IterativeImputer] Completing matrix with shape (10, 3)
[IterativeImputer] Change: 81.47029319282518, scaled tolerance: 0.222 
[IterativeImputer] Change: 18.77192329141039, scaled tolerance: 0.222 
[IterativeImputer] Change: 3.88396557634249, scaled tolerance: 0.222 
[IterativeImputer] Change: 0.8962098822958637, scaled tolerance: 0.222 
[IterativeImputer] Change: 0.2623677437495502, scaled tolerance: 0.222 


C:\Users\vinod\anaconda3\lib\site-packages\sklearn\impute\_iterative.py:669: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn("[IterativeImputer] Early stopping criterion not"


array([[ 25.        ,  16.01987637,  50.        ],
       [ 27.        ,   3.        , 147.29165923],
       [ 29.        ,   5.        , 110.        ],
       [ 31.        ,   7.        , 140.        ],
       [ 33.        ,   9.        , 170.        ],
       [ 68.68353139,  11.        , 200.        ],
       [ 80.        ,   6.        , 237.31832187],
       [ 97.        ,  13.        , 222.        ],
       [ 42.        ,  15.        , 150.        ],
       [ 33.16781311,  16.        ,  90.        ]])

In [31]:
from sklearn.model_selection import train_test_split

In [35]:
x=pd.DataFrame({"age":[25,27,29,31,33,np.NaN,80,97,42,np.NaN],
                "experience":[np.NaN,3,5,7,9,11,6,13,15,16],
                "salary":[50,np.NaN,110,140,170,200,np.NaN,222,150,90]})

In [37]:
x_train

age  experience  salary
0  25.0         NaN    50.0
1  27.0         3.0     NaN
2  29.0         5.0   110.0
3  31.0         7.0   140.0
4  33.0         9.0   170.0
5   NaN        11.0   200.0
6  80.0         6.0     NaN
7  97.0        13.0   222.0
8  42.0        15.0   150.0
9   NaN        16.0    90.0

In [90]:
x_train,x_test=train_test_split(x,test_size=0.2,shuffle=False)

In [91]:
x_test

age  experience  salary
8  42.0        15.0   150.0
9   NaN        16.0    90.0

In [92]:
x_test

age  experience  salary
8  42.0        15.0   150.0
9   NaN        16.0    90.0

In [56]:
imp.imputation_sequence_

[_ImputerTriplet(feat_idx=0, neighbor_feat_idx=array([1, 2]), estimator=LinearRegression()),
 _ImputerTriplet(feat_idx=1, neighbor_feat_idx=array([0, 2]), estimator=LinearRegression()),
 _ImputerTriplet(feat_idx=2, neighbor_feat_idx=array([0, 1]), estimator=LinearRegression()),
 _ImputerTriplet(feat_idx=0, neighbor_feat_idx=array([1, 2]), estimator=LinearRegression()),
 _ImputerTriplet(feat_idx=1, neighbor_feat_idx=array([0, 2]), estimator=LinearRegression()),
 _ImputerTriplet(feat_idx=2, neighbor_feat_idx=array([0, 1]), estimator=LinearRegression()),
 _ImputerTriplet(feat_idx=0, neighbor_feat_idx=array([1, 2]), estimator=LinearRegression()),
 _ImputerTriplet(feat_idx=1, neighbor_feat_idx=array([0, 2]), estimator=LinearRegression()),
 _ImputerTriplet(feat_idx=2, neighbor_feat_idx=array([0, 1]), estimator=LinearRegression()),
 _ImputerTriplet(feat_idx=0, neighbor_feat_idx=array([1, 2]), estimator=LinearRegression()),
 _ImputerTriplet(feat_idx=1, neighbor_feat_idx=array([0, 2]), estimato

In [102]:
imp.transform(x_train)

[IterativeImputer] Completing matrix with shape (8, 3)


array([[ 25.        ,  16.01987637,  50.        ],
       [ 27.        ,   3.        , 147.29165923],
       [ 29.        ,   5.        , 110.        ],
       [ 31.        ,   7.        , 140.        ],
       [ 33.        ,   9.        , 170.        ],
       [ 68.68353139,  11.        , 200.        ],
       [ 80.        ,   6.        , 237.31832187],
       [ 97.        ,  13.        , 222.        ]])

In [88]:
x_train.mean()

age            46.000000
experience      7.714286
salary        148.666667
dtype: float64

In [97]:
imp.transform(x_test)

[IterativeImputer] Completing matrix with shape (2, 3)


array([[ 42.        ,  15.        , 150.        ],
       [ 33.16781311,  16.        ,  90.        ]])

In [98]:
imp.imputation_sequence_

[_ImputerTriplet(feat_idx=0, neighbor_feat_idx=array([1, 2]), estimator=LinearRegression()),
 _ImputerTriplet(feat_idx=1, neighbor_feat_idx=array([0, 2]), estimator=LinearRegression()),
 _ImputerTriplet(feat_idx=2, neighbor_feat_idx=array([0, 1]), estimator=LinearRegression()),
 _ImputerTriplet(feat_idx=0, neighbor_feat_idx=array([1, 2]), estimator=LinearRegression()),
 _ImputerTriplet(feat_idx=1, neighbor_feat_idx=array([0, 2]), estimator=LinearRegression()),
 _ImputerTriplet(feat_idx=2, neighbor_feat_idx=array([0, 1]), estimator=LinearRegression()),
 _ImputerTriplet(feat_idx=0, neighbor_feat_idx=array([1, 2]), estimator=LinearRegression()),
 _ImputerTriplet(feat_idx=1, neighbor_feat_idx=array([0, 2]), estimator=LinearRegression()),
 _ImputerTriplet(feat_idx=2, neighbor_feat_idx=array([0, 1]), estimator=LinearRegression()),
 _ImputerTriplet(feat_idx=0, neighbor_feat_idx=array([1, 2]), estimator=LinearRegression()),
 _ImputerTriplet(feat_idx=1, neighbor_feat_idx=array([0, 2]), estimato

In [99]:
print(imp.imputation_sequence_[0][2].coef_)

[1.07232676 0.33999682]


In [100]:
print(imp.imputation_sequence_[0][2].intercept_)

-11.352363309466888


In [72]:
 (0.05657303*16)+(-0.00801088*90)+(7.869452942621407)

8.053642222621407

In [101]:
1.07232676*16+ 0.33999682*90 -11.352363309466888

36.404578650533104